### ISSUE TITLE
Case folding

### ISSUE THREAD

**Issue by 89z** [benhoyt/countwords#25]
I see some version of `tolower` being used in different places:

https://github.com/benhoyt/countwords/blob/9d81d13711e56c25068893880a648ac96d0fa92e/optimized.py#L17
https://github.com/benhoyt/countwords/blob/9d81d13711e56c25068893880a648ac96d0fa92e/simple.go#L16
https://github.com/benhoyt/countwords/blob/9d81d13711e56c25068893880a648ac96d0fa92e/simple.py#L6

I just wanted to point out, while proper unicode folding is the best option, if you are sticking to something like this, `toupper` is the better option:

- https://stackoverflow.com/questions/11124705#65433126
- https://stackoverflow.com/questions/234591#65451148
- https://stackoverflow.com/questions/40250988#65452097

**Comment by benhoyt** [comment]
From my tests, it's actually the other way around. Currently `simple.go` takes about 1.1 seconds to run on my machine, but if I change the `strings.ToLower` to `strings.ToUpper`, it consistently takes closer to 1.4 seconds (30% slower). I believe this is because there are many more words that are already lowercase, so `ToLower` doesn't have to allocate a new string in that case, just scan the characters and ensure they're all lowercase already. See https://github.com/golang/go/blob/2d4042d4ab3a2021819dce91eb228daf8fa5e557/src/strings/strings.go#L593

Most words are already lowercase in the input I'm using, but also in most texts.

**Comment by 89z** [comment]
sorry I wasnt clear. What I meant was, by using `ToLower` or similar, in some situations, words that should match wont.

This will still be a problem with `ToUpper` as well, but to a lesser extent. However I can understand if you want to sacrifice accuracy for speed.

**Comment by benhoyt** [comment]
Ah, I see, thanks. Yeah, I think I'll leave as is for now.
