### ISSUE TITLE
Simple Python: use generator comprehension

### ISSUE THREAD

**Issue by Senpos** [benhoyt/countwords#64]
Hey there!

If you use generator comprehension in a [Python simple version](https://github.com/benhoyt/countwords/blob/3352b3e20070de46148b8b634d119f33168af06a/simple.py), you can get some free performance without sacraficing readbility (at least, not too much 😅).

```python
import sys
import collections


counts = collections.Counter(
    word
    for line in sys.stdin
    for word in line.lower().split()
)

for word, count in counts.most_common():
    print(word, count)
```

On my computer, it went from ~258ms to 215ms. :)

Yep, using a comprehension is faster than calling a function many times.

**Comment by benhoyt** [comment]
Thanks for the contribution. However, I don't think it's simpler -- I've always thought nested comprehensions were hard to read, because I always forget which order they go in (is it inner first? outer first?). This is not the way I'd write it as a long-time Python guy ... unless I were trying to optimize. So I think I'll leave it as is, and leave the optimizations for `optimized.py`. Thanks anyway!
