### ISSUE TITLE
Gforth 0.7.3 (Latest release) does not accept it

### ISSUE THREAD

**Issue by chmykh** [benhoyt/countwords#79]
Both simple.fs and optimized.fs do not work with Gforth 0.7.3 (Latest release). The undefined words are:
name>interpret
traverse-wordlist
find-name-in

**Comment by benhoyt** [comment]
Yeah, I know. Unfortunately it seems that [0.7.3](https://github.com/forthy42/gforth/commits/v0-7-3) was released in 2014 and there hasn't been an official Gforth release since then (!). There are a lot of new features that have been added since then (`traverse-wordlist`, etc), so I built from the latest source. It's looks they create release tags every few days (but not actual package manager releases): https://github.com/forthy42/gforth/releases
